<?php
/**
 * Created by PhpStorm.
 * User: dns
 * Date: 16.02.18
 * Time: 17:37
 */

namespace App\Controller\FOSUserBundle;


use App\Service\OAuthService;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;

class SecurityController extends \FOS\UserBundle\Controller\SecurityController
{
    /**
     * @var OAuthService
     */
    private $service;

    public function __construct(OAuthService $service, CsrfTokenManagerInterface $tokenManager = null)
    {
        $this->service = $service;
        parent::__construct($tokenManager);
    }


    protected function renderLogin(array $data)
    {
        $data['fb_link'] = $this->service->getFacebookLink();

        return parent::renderLogin($data); // TODO: Change the autogenerated stub
    }


}